name: iOS CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: macos-14

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Build the app
      run: |
        xcodebuild clean build \
          -workspace TravelWorld.xcworkspace \
          -scheme TravelWorld \
          -destination 'platform=iOS Simulator,name=iPhone 15' \
          CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
