name: iOS CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Xcode
      run: sudo xcode-select -s /Applications/Xcode_15.3.app # or whatever version you need

    - name: Build app
      run: |
        xcodebuild clean build \
          -workspace YourApp.xcworkspace \  # OR use -project if not using workspaces
          -scheme YourScheme \
          -destination 'platform=iOS Simulator,name=iPhone 15' \
          CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO

    - name: Run tests
      run: |
        xcodebuild test \
          -workspace YourApp.xcworkspace \
          -scheme YourScheme \
          -destination 'platform=iOS Simulator,name=iPhone 15'
